### PR TITLE
bugfix/667

### LINKED ISSUE #667: Aircraft cleared twice for ILS approach do not capture glideslope
Browser: Chrome
Airport: All

#### Issue Description
Aircraft that are given a turn and cleared for an ILS approach _twice_ before actually intercepting the localizer are not descending along the glideslope. They remain at the last assigned altitude until crossing the runway threshold, then complete the descent.

#### Steps to reproduce
1. Position an aircraft where they can be assigned a new heading to intercept the localizer, at an altitude below the glideslope altitude where they are to intercept.
1. In one command, issue the aircraft a turn to the intercept heading, and clear them for the approach, eg `T L 160 ILS 16R`.
1. Verify the projection shows the aircraft joining the localizer.
1. Before they have joined the localizer, enter the same command for the same aircraft (eg `T L 160 ILS 16R`).
1. Observe aircraft join the localizer, but never descend along the glideslope.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #667.

Fix bug where aircraft cleared twice for ILS won't join the glideslope.

### CODE REVIEW

File: src/assets/scripts/client/aircraft/AircraftCommander.js [hunk 1]
```diff
@@ -260,7 +259,7 @@ export default class AircraftCommander {
         aircraft.target.turn = direction;
 
         if (aircraft.hasApproachClearance) {
-            aircraft.cancelApproachClearance(aircraft.altitude, aircraft.heading);
+            aircraft.cancelApproachClearance(aircraft);
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/AircraftCommander.js]: You could probably drop the aircraft param here too and just use`this` when in `.cancelApproachClearance()`

Comment (n8rzz) [inline src/assets/scripts/client/aircraft/AircraftCommander.js]: Do we need the aircraft param here?

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js [hunk 2]
```diff
@@ -409,24 +409,23 @@ export default class Pilot {
...
+     * @return {array} [success of operation, readback]
      */
-    cancelApproachClearance(currentAltitude, currentHeading) {
+    cancelApproachClearance(aircraftModel) {
         if (!this.hasApproachClearance) {
             return [false, 'we have no approach clearance to cancel!'];
         }
 
         const airport = AirportController.airport_get();
         const altitudeToMaintain = Math.max(
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/Pilot/Pilot.js]: Could you break this up a bit more?  I'm not a fan of the nested `Math` calls here

File: src/assets/scripts/client/aircraft/AircraftCommander.js (hunk 1 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: Thanks for pointing this out, because it doesn't look right for an entirely different reason: `.cancelApproachClearance()` is not a property of the aircraft at all, but rather the pilot. Fixed that mistake right up!

It is for that reason that we actually do have to pass the aircraft (or at least a couple of its properties) to the pilot, since he does not have access to it for reasons of circularity (possibly a word?).

That's actually a pattern I think would be wise with the pilot rather than passing hundreds of individual properties to the pilot when he completes an action: let him take a look at the entire aircraft, and then manipulate the mcp and fms appropriately. I suppose we could even remove his local references if desired. That's all beyond the scope of this anyway, but food for thought?

Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: see above

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js (hunk 2 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/Pilot/Pilot.js]: done!
