### PR TITLE
bugfix/148

### LINKED ISSUE #148: `hold` command causes crash
If a user gives the `hold` command to an arrival aircraft, the game crashes.

```
AircraftFlightManagementSystem.js:896 Uncaught TypeError: undefined is not a function
    at AircraftFlightManagementSystem.get (AircraftFlightManagementSystem.js:896)
    at AircraftFlightManagementSystem.altitudeForCurrentWaypoint (AircraftFlightManagementSystem.js:1034)
    at Aircraft.updateTarget (AircraftInstanceModel.js:1989)
    at Aircraft.update (AircraftInstanceModel.js:2651)
    at AircraftController.aircraft_update (AircraftController.js:180)
    at AirportController.recalculate (AirportController.js:78)
    at App.update (App.js:321)
    at App.js:318
```

Originally reported in zlsa/atc#782.

### PR DESCRIPTION
**Pull request by erikquinn**
Ensure hold command generates Waypoint instance, and not just an object. This fixes an error when trying to call a method of the Waypoint model, which obviously doesn't exist if it's not an instance of that class!

Holds work properly now.

Resolves #148.

### CODE REVIEW

File: src/assets/scripts/client/aircraft/AircraftCommander.js [hunk 1]
```diff
@@ -581,31 +581,23 @@ export default class AircraftCommander {
...
                 waypoints: [
-                    { // document the present position as the 'fix' we're holding over
-                        navmode: WAYPOINT_NAV_MODE.FIX,
-                        fix: '[custom]',
-                        location: holdFixLocation,
-                        altitude: aircraft.fms.altitudeForCurrentWaypoint(),
-                        speed: aircraft.fms.currentWaypoint.speed
-                    },
-                    { // Force the initial turn to outbound heading when entering the hold
+                    new Waypoint({
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/AircraftCommander.js]: for readability, this instantiation should be pulled out and assigned to a variable.

Comment (erikquinn) [inline src/assets/scripts/client/aircraft/AircraftCommander.js]: Fixed. 👍

File: CHANGELOG.md [hunk 2]
```diff
@@ -39,7 +39,7 @@
 - Ensures data block colored bars are all the same width (3px), regardless of callsign length [#210](https://github.com/openscope/openscope/issues/210)
 - Adds missing `return` in `.generateFlightNumberWithAirlineModel()` that was needed to properly recurse back through the method in the case of a duplicate flight number. [#210](https://github.com/openscope/openscope/issues/210)
 - Updates boolean logic in `App.updateViewControls()` which was evaluating an asynchronous property that, typically, had not finished loading. [#203](https://github.com/openscope/openscope/issues/203)
-
+- Fixes internal fms error that was breaking the game when issuing holds over present posiion [#148](https://github.com/openscope/openscope/issues/148)
```
Comment (n8rzz) [inline CHANGELOG.md]: `posiion` => `position`

File: src/assets/scripts/client/aircraft/AircraftCommander.js [hunk 3]
```diff
@@ -581,32 +581,24 @@ export default class AircraftCommander {
             holdFixLocation = aircraft.position; // make a/c hold over their present position
             inboundHdg = aircraft.heading;
 
-            // TODO: these aren't `Waypoints` and they should be
+            const holdingWaypointModel = new Waypoint({
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/AircraftCommander.js]: 👍

File: CHANGELOG.md (hunk 2 above)
Comment (n8rzz) [inline CHANGELOG.md]: bump

just this little spelling fix and this can go in.

Comment (erikquinn) [inline CHANGELOG.md]: Fixed.

File: CHANGELOG.md [hunk 4]
```diff
@@ -48,7 +48,7 @@
 - Updates airline json files to include `icao` key. Updates `AirlineCollection` and `AirlineModel` to handle variable casing of `icao`  [#195](https://github.com/openscope/openscope/issues/195)
 - Adds a default position value to `SpawnPatternModel` so aircraft have, at least, a `[0, 0]` starting position [#207](https://github.com/openscope/openscope/issues/207)
 - Ensures data block colored bars are all the same width (3px), regardless of callsign length [#210](https://github.com/openscope/openscope/issues/210)
-
+- Fixes internal fms error that was breaking the game when issuing holds over present position [#148](https://github.com/openscope/openscope/issues/148)
```
Comment (n8rzz) [inline CHANGELOG.md]: 👍
