### PR TITLE
enhancement/1715 - Sync fast-forward menu button with timewarp system commands

### LINKED ISSUE #1715: timewarp system command should update fast-forward menu button state
Browser: chrome (any)

Airport: any

Approximate play time before issue: n/a

#### Issue Description
Using the `timewarp` system command does not update the state of the fast-forward menu button.

#### Steps to reproduce
- Use fast-forward button to adjust time warp, note button state change reflects: blue = 2x; red = 5x.
- Adjust timewarp using `timewarp` system command, button does not change

#### Proposed solution
- timewarp system command with 2x to 4x speed should map to "blue" state (title: Set time warp to 5)
- timewarp system command with 5x speed should map to "red" state (title: Reset time warp)

### LINKED ISSUE #1716: timewarp system command accepts negative numbers, breaks simulation
Browser: chrome (any)

Airport: any

Approximate play time before issue: n/a

#### Issue Description
The `timewarp` system command will accept a negative argument. This will break the simulation.

#### Steps to reproduce
- try input `timewarp -1`

### PR DESCRIPTION
**Pull request by cake-pie**
Resolves #1715
Resolves #1716

The purpose of this pull request is to:

- make the fast-forward menu button synchronize with any manually issued `timewarp` system commands
- prevent attempts to travel backward in time :stuck_out_tongue_closed_eyes:

### CODE REVIEW

**Comment by cake-pie** [comment]
I suppose I could also check for and ignore NaN to address #1249, but that issue is probably better addressed by making the parser more tolerant of extra spaces.

File: src/assets/scripts/client/game/GameController.js [hunk 1]
```diff
@@ -261,11 +261,28 @@ class GameController {
...
+            return;
+        } else if (nextValue < 0) {
             return;
         }
 
         TimeKeeper.updateSimulationRate(nextValue);
+        EventTracker.recordEvent(TRACKABLE_EVENT.OPTIONS, 'timewarp', nextValue);
+
+        const $fastForwards = $(SELECTORS.DOM_SELECTORS.FAST_FORWARDS);
+        if (nextValue === 1) {
```
Comment (n8rzz) [inline src/assets/scripts/client/game/GameController.js:273]: missing empty line above `if` statement

**Review by n8rzz — APPROVED** [review]
just that one little nit pick on spacing.  looks good!
