### PR TITLE
bugfix/1240 - Fix readback from departures in runway queue is not correct

### LINKED ISSUE #1240: Readback from departures in runway queue is not correct
The messages about not being first in line for the runway (when trying to clear someone for takeoff) are not correctly getting the aircraft callsign, because they expect the runway queue to contain instances of `AircraftModel`, when in fact, they contain the aircraft IDs. The aircraft can be looked up by these IDs instead to achieve the desired result.

#### Steps to reproduce
1. Taxi a departure to a runway.
1. Taxi another departure to the same runway.
1. Wait at least three seconds to allow them to both reach the runway).
1. Clear the _second_ aircraft for takeoff (this will be the one whose data block is _not_ shown).
1. Observe the response using `undefined`, etc, instead of correct callsigns.

### PR DESCRIPTION
**Pull request by felixscheffer**
Resolves #1240

### CODE REVIEW

File: src/assets/scripts/client/aircraft/AircraftController.js [hunk 1]
```diff
@@ -383,18 +383,35 @@ export default class AircraftController {
...
     /**
+     * Finds an aircraft by its callsign
+     *
      * @method findAircraftByCallsign
      * @param  {string} [callsign='']
      * @return {AircraftModel|null}
      */
     findAircraftByCallsign(callsign = '') {
-        if (callsign === '') {
+        if (!callsign) {
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/AircraftController.js]: I like this better, but perhaps we should change the default assignment to `null` then instead of an empty string?

File: src/assets/scripts/client/aircraft/AircraftController.js [hunk 2]
```diff
@@ -383,18 +383,35 @@ export default class AircraftController {
...
             return null;
         }
 
         return _find(this.aircraft.list, (aircraft) => aircraft.callsign.toLowerCase() === callsign.toLowerCase());
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/AircraftController.js]: could you add a `TODO` here to normalize `callsign` casing?  in my opinion, the only thing we should need to lowerCase here would be the passed value

File: src/assets/scripts/client/aircraft/AircraftController.js [hunk 3]
```diff
@@ -383,18 +383,35 @@ export default class AircraftController {
...
     }
 
+    /**
+     * Finds an aircraft by its internal id
+     *
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/AircraftController.js]: _why_ would be need to find and aircraft by an internal ID?  don't we reference aircraft by their callsigns? 

I know the answer here, but we should document this reason for our future selves.

Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/AircraftController.js]: That's good because I have no idea why we use the internal ID in the runway queue. 🙈

File: src/assets/scripts/client/aircraft/AircraftController.js (hunk 1 above)
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/AircraftController.js]: Good point

Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/AircraftController.js]: done

File: src/assets/scripts/client/aircraft/AircraftController.js [hunk 4]
```diff
@@ -383,16 +383,35 @@ export default class AircraftController {
...
-     * @param  {string} [callsign='']
+     * @param  {string} [callsign=null]
+     * @return {AircraftModel|null}
+     */
+    findAircraftByCallsign(callsign = null) {
+        if (!callsign) {
+            return null;
+        }
+
+        const normalizedCallSign = callsign.toUpperCase();
```
Comment (felixscheffer) [inline src/assets/scripts/client/aircraft/AircraftController.js]: @n8rzz I tried to evolve your previous comment here (see `AircraftModel get callsign()`)

File: src/assets/scripts/client/aircraft/AircraftController.js (hunk 3 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftController.js]: I don't remember either.. I think it was some circular dependency issue, where we added the id because we couldn't store the AircraftModel? I dunno.

File: src/assets/scripts/client/aircraft/AircraftController.js (hunk 2 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftController.js]: addressed below

File: src/assets/scripts/client/aircraft/AircraftController.js [hunk 5]
```diff
@@ -383,16 +383,35 @@ export default class AircraftController {
...
+     *
+     * @method findAircraftById
+     * @param  {string} [id]
      * @return {AircraftModel|null}
      */
-    findAircraftByCallsign(callsign = '') {
-        if (callsign === '') {
+    findAircraftById(id) {
+        if (!id) {
             return null;
```
[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftController.js]: done
