### PR TITLE
bugfix/685

### LINKED ISSUE #685: Up/down arrows should insert command instead of non-existent character
Browser: All

Airport: All

Approximate play time before issue: N/A

#### Issue Description
_please include any console errors and/or screenshots_ 
When using the altitude change hotkeys (up/down arrow), a "not found" character is displayed. This should be changed to insert the command.

#### Steps to reproduce
- Select aircraft
- Use arrow keys to change altitude

### PR DESCRIPTION
**Pull request by sam-irl**
Resolves #685 

The purpose of this pull request is to insert `altitude` into the command bar instead of the unicode arrow char which does not exist in the default font

### CODE REVIEW

File: src/assets/scripts/client/InputController.js [hunk 1]
```diff
@@ -484,7 +484,7 @@ export default class InputController {
                 break;
             case KEY_CODES.UP_ARROW:
                 if (this._isArrowControlMethod()) {
-                    this.$commandInput.val(`${currentCommandInputValue} \u2B61 `);
+                    this.$commandInput.val(`${currentCommandInputValue} altitude `);
```
Comment (erikquinn) [inline src/assets/scripts/client/InputController.js]: Let's keep the directional context here by using `c` for climb.

File: src/assets/scripts/client/InputController.js [hunk 2]
```diff
@@ -505,7 +505,7 @@ export default class InputController {
                 break;
             case KEY_CODES.DOWN_ARROW:
                 if (this._isArrowControlMethod()) {
-                    this.$commandInput.val(`${currentCommandInputValue} \u2B63 `);
+                    this.$commandInput.val(`${currentCommandInputValue} altitude `);
```
Comment (erikquinn) [inline src/assets/scripts/client/InputController.js]: Let's keep the directional context here by using `d` for descend.

File: src/assets/scripts/client/commandParser/commandMap.js [hunk 3]
```diff
@@ -33,8 +33,6 @@ export const SYSTEM_COMMANDS = {
  * @final
  */
 const UNICODE_COMMANDS = {
-    '\\u2B61': 'altitude',
-    '\\u2B63': 'altitude',
     '\\u2BA2': 'heading',
     '\\u2BA3': 'heading',
```
Comment (erikquinn) [inline src/assets/scripts/client/commandParser/commandMap.js]: These two are also no longer used. Since we're already here, might as well remove them also.

Comment (erikquinn) [reply src/assets/scripts/client/commandParser/commandMap.js]: done
