### PR TITLE
bugfix/1034 - fix waypoint time-to-turn calculations

### LINKED ISSUE #935: Aircrafts are skipping a fix
Airport: OTHH (#857)

#### Issue Description
Screenshot
The route of the aircraft should be ELEDA-MEBTI-BOSUP-... 
But after ELEDA the aircraft skipping MEBTI and turns inbound BOSUP.

#### Steps to reproduce
That's applicable to the following SIDs: BATHA1E, BUNDU1E, NAMLA1E, SALWA1E
(At the current version of the airport MEBTI defined as a fly-over fix in order to prevent this)

### LINKED ISSUE #1034: Waypoint time-to-turn calculations are slightly off
Discovered during the work on #937, the calculations (which could never be figured out because they're old and without labels/explanations) turned out to actually be slightly off. They should be reworked and better documented so we can clearly see how the calculations work.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #1034
Resolves #935

Fix waypoint time-to-turn calculations.

The errors were fairly minimal, but became quite noticeable at very high ground speeds from the en route demo. They were constantly undershooting the turn, whereas with this they will cut the corner properly and end up right on the targeted track.

### CODE REVIEW

File: src/assets/scripts/client/math/flightMath.js [hunk 1]
```diff
@@ -25,27 +25,34 @@ import {
...
- * @return {number}
+ * @param speed {number} aircraft groundspeed, in knots
+ * @param bankAngle {number} bank angle to use, in radians
+ * @return {number} radius of turn, in nautical miles
  */
-export const calcTurnRadius = (speed, bankAngle) => {
-    return (speed * speed) / (PHYSICS_CONSTANTS.GRAVITATIONAL_MAGNITUDE * tan(bankAngle));
-};
+export function calcTurnRadius(speed, bankAngle) {
+    return (speed * speed) / (68416 * Math.tan(bankAngle));
```
Comment (n8rzz) [inline src/assets/scripts/client/math/flightMath.js]: Does this 68416 have a name we can use for a constant?

File: src/assets/scripts/client/math/flightMath.js [hunk 2]
```diff
@@ -25,27 +25,34 @@ import {
...
  * @return {number}
  */
-export const calcTurnInitiationDistance = (speed, bankAngle, courseChange) => {
-    const turnRadius = calcTurnRadius(speed, bankAngle);
+export function calcTurnInitiationDistanceNm(speed, bankAngle, courseChange) {
+    const turnRadiusNm = calcTurnRadius(speed, bankAngle);
 
-    return turnRadius * tan(courseChange / 2) + speed;
-};
+    return turnRadiusNm * (courseChange / 2) / (Math.PI / 2);
```
Comment (n8rzz) [inline src/assets/scripts/client/math/flightMath.js]: Break out these `/ 2` items to variables

File: src/assets/scripts/client/math/flightMath.js (hunk 1 above)
Comment (erikquinn) [reply src/assets/scripts/client/math/flightMath.js]: it's kinda just a constant. we can call it `const conversionFactor = 68416;` if you like.

Comment (erikquinn) [reply src/assets/scripts/client/math/flightMath.js]: done

File: src/assets/scripts/client/math/flightMath.js (hunk 2 above)
Comment (erikquinn) [reply src/assets/scripts/client/math/flightMath.js]: done

**Comment by felixscheffer** [comment]
Update:

1.  calculate the turn initiation distances based on turnRadius * tan(angle*0.5)
2.  calculate the turn radius based on turn rate (like we do, when we actually turn the aircraft) instead of using bank angle.
3.  wind is constantly pushing the aircraft off the track. I think there is a ticket for this issue but if there is none, we should definitely create one.
4. calculate the turn initiation distances based on the aircraft's target heading instead of its actual heading to prevent the aircraft from skipping fixes.

@erikquinn  Is there an easy way to see if these changes work for the enroute demo (#937)?

**Comment by erikquinn** [comment]
Approved!
