### PR TITLE
bugfix/364

### LINKED ISSUE #364: System commands with no arguments not working
For example, the command `version` should print the simulator version to the console.

Within the CommandParser, this fails at `#_buildSystemCommandModel)` when called at line 150. It seems to expect _either_ a callsign _or_ an argument. For example, `timewarp` takes an argument and works just fine, but those that have neither aren't handled correctly.

Additionally, if those commands that _expect_ arguments (like timewarp) don't receive them, they may not be working properly. `timewarp` alone results in the canvas going blank, which could either be an issue with the parser freaking out, or it could be working properly, and the canvas can't figure out what to do when time stops (in which case, we should enforce a default argument of `1` in the parser to prevent this).

### PR DESCRIPTION
**Pull request by n8rzz**
Resolves #364.

Repairs system commands that were not being parsed correctly so they can be used in-game.

### CODE REVIEW

File: src/assets/scripts/client/commandParser/argumentParsers.js [hunk 1]
```diff
@@ -173,3 +173,25 @@ export const holdParser = (args) => {
...
+/**
+ * the `timewarp` command needs to be able to provide a default value,
+ * this parser allows us to do that.
+ *
+ * @method timewarpParser
+ * @param  {array|undefined} [args=[]]
+ * @return {array<number>}
+ */
+export const timewarpParser = (args = []) => {
+    const defaultTimewarpValue = 0;
```
Comment (erikquinn) [inline src/assets/scripts/client/commandParser/argumentParsers.js]: Should be `1`.

File: src/assets/scripts/client/commandParser/argumentParsers.js [hunk 2]
```diff
@@ -173,3 +173,25 @@ export const holdParser = (args) => {
...
+
+    if (args.length === 0) {
+        return [defaultTimewarpValue];
+    }
+
+    // calling method is expecting an array with values that will get spread later, thus we purposly
+    // return an array here
+    return [
+        convertStringToNumber(args[0])
```
Comment (erikquinn) [inline src/assets/scripts/client/commandParser/argumentParsers.js]: Is this better than plain old `parseInt()` or `parseFloat()`?

Comment (n8rzz) [inline src/assets/scripts/client/commandParser/argumentParsers.js]: well, this actually _is_ `parseInt`.  I've just wrapped inside a function name that provides a little more context on the intent.  I did this because this little guy gets used a lot in the `CommandParser` files and I didn't want to have to keep writing it.

File: src/assets/scripts/client/commandParser/argumentParsers.js (hunk 1 above)
Comment (n8rzz) [inline src/assets/scripts/client/commandParser/argumentParsers.js]: :facepalm:

Comment (n8rzz) [inline src/assets/scripts/client/commandParser/argumentParsers.js]: fixed

File: src/assets/scripts/client/commandParser/argumentParsers.js (hunk 2 above)
Comment (erikquinn) [inline src/assets/scripts/client/commandParser/argumentParsers.js]: Seems goofy, but whatever floats your boat... ⛵
