### PR TITLE
bugfix/1395 - Fix aircraft's wind correction angle math

### LINKED ISSUE #1395: Aircraft climbing on glideslope on short final
Browser:
Chrome
Airport:
Boston Logan
Approximate play time before issue:

#### Issue Description
Flights end up increasing altitude after descending to about 1000 Ft while approaching runway 27. 
After clearing for ILS 27 flights end up way after runway 27.
OBSERVE NKS 5577
NKS 5577 HAS STARTED DESCENDING
NKS 5577 RISING
KEPT ON RISING  UPTO 2500
THEN ARRIVES

#### Steps to reproduce
-

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #1395.

### CODE REVIEW

File: src/assets/scripts/client/aircraft/AircraftModel.js [hunk 1]
```diff
@@ -2252,19 +2278,42 @@ export default class AircraftModel {
...
+            // TODO: This is copied from this.updateGroundSpeedPhysics(). Should be moved somewhere it's used by both
+            // Calculate wind vector
+            const windIncreaseFactorPerFoot = 0.00002; // 2.00% per thousand feet
+            const { wind } = AirportController.airport_get();
+            const windTravelDirection = wind.angle + Math.PI;
+            const windTravelSpeedAtSurface = wind.speed;
+            const windTravelSpeed = windTravelSpeedAtSurface * (1 + (this.altitude * windIncreaseFactorPerFoot));
+            const windVector = vscale(vectorize_2d(windTravelDirection), windTravelSpeed);
+
+            this.targetHeading = vradial(vsub(groundTrackVector, windVector));
```
Comment (erikquinn) [inline src/assets/scripts/client/aircraft/AircraftModel.js]: Don't change the target heading or target ground track. Simply get the heading to use rather than changing stuff:
```
let targetHeading = this.targetHeading;

if (_isNil(targetHeading)) {
    targetHeading = this.calculateCrabHeadingForGroundTrack(this.targetGroundTrack);
}
```

Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftModel.js]: done!

File: src/assets/scripts/client/aircraft/AircraftModel.js [hunk 2]
```diff
@@ -528,6 +536,24 @@ export default class AircraftModel {
         }
     }
 
+    get targetHeading() {
+        return this._targetHeading;
```
[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftModel.js]: done!

**Comment by erikquinn** [comment]
This is now fully working, just needs tests.

File: src/assets/scripts/client/airport/AirportModel.js [hunk 3]
```diff
@@ -556,25 +557,25 @@ export default class AirportModel {
...
-        // wind.angle += extrapolate_range_clamp(-1, angle_factor, 1, degreesToRadians(-4), degreesToRadians(4));
-        // wind.speed *= extrapolate_range_clamp(-1, speed_factor, 1, 0.9, 1.05);
-        //
-        // return wind;
+     * @method getWindAtAltitude
+     * @param {number} altitude
+     * @returns {object<angle, speed>}
+     */
+    getWindAtAltitude(altitude = this.elevation) {
+        const windIncreaseFactorPerFoot = 0.00002; // 2.00% per thousand feet
```
Comment (n8rzz) [inline src/assets/scripts/client/airport/AirportModel.js]: should this live in a constants file somewhere?

Comment (erikquinn) [reply src/assets/scripts/client/airport/AirportModel.js]: probably, yep. done.
