### PR TITLE
bugfix/1398 - Improve aircraft slowing behavior on final approach

### LINKED ISSUE #1398: E135 on the glideslope keeps high speed, then goes around because of it
Related: #1228.

Browser: Firefox Quantum 67.0 (64-bit)

Openscope: v6.13.0

Airport: EDDH

Approximate play time before issue: 30 minutes game time

#### Issue Description

The E135 aircraft keeps the high airspeed of about 260kt on the glideslope until about ~1800ft. Then it tries to slow down, but can't slow don't in time an issue a go around. This issue is related to https://github.com/openscope/openscope/issues/1228. Other aircrafts slow down earlier and have enough time to slide down in time and land successfully.

I tried it with different altitudes to intercept the localizer. When I let it intercept at 4000ft it will use the glideslope as expected, but it does not slow down until it is too late. The aircraft should slow down on the glideslope sooner. If I lower the speed manually with something like "CALLSGN - 170" it can land successfully.

#### Steps to reproduce

* Spawn/wait for an E135 aircraft
* Intercept the localizer at different altitudes like 2000ft, 3000ft or 4000ft.
* Watch the aircraft going down the glideslope, keeping about 260kt speed.
* Aircraft goes around at ~1800ft or ~8nm to the runway, going back to 3000ft.

### PR DESCRIPTION
**Pull request by erikquinn**
Resolves #1398.

### ~~DO NOT MERGE UNTIL UNDOING KSEA/ASQ CHANGES~~ (reverted)

---

#### Compared with develop branch: https://openscope-pr-1530-control.herokuapp.com/

---

Note: The second link is the develop branch with KSEA changed to use all E135s to make it easy to see the before/after.

### CODE REVIEW

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js [hunk 1]
```diff
@@ -145,6 +145,7 @@ export default class Pilot {
         this.cancelApproachClearance(aircraftModel);
         this._mcp.setAltitudeFieldValue(clampedAltitude);
         this._mcp.setAltitudeHold();
+        this._mcp.shouldExpediteAltitudeChange = false;
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/Pilot/Pilot.js]: Missing empty line between assignment and method call

**Comment by erikquinn** [comment]
KSEA/ASQ changes reverted for merge.
