### PR TITLE
bugfix/955 - Overhaul `sid` command

### LINKED ISSUE #955: SID Command doesn't work
Browser: Google Chrome

Airport: All

Approximate play time before issue: Any

#### Issue Description
I type in "AAL1123 sid ABQ3" (for example) and it puts up a message "SID name not understood. Any possibility of either deprecating or fixing the command?

### PR DESCRIPTION
**Pull request by eoinbutler**
Resolves openscope/openscope#955

The purpose of this pull request is to restore the functionality of the `sid` and `star` commands

### CODE REVIEW

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 1]
```diff
@@ -793,9 +793,21 @@ export default class Fms {
...
     replaceDepartureProcedure(routeString) {
-        const routeStringElements = routeString.split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
-
-        if (routeStringElements.length !== 3) {
+        var routeStringElements = routeString.split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
+
+        // if routeString contains an entry element, use that as the departure runway
+        // otherwise, keep the departure runway already defined
+        // complain if there is no departure runway defined
+        if (routeStringElements.length === 2 ) {
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: If like for you to look at this whole block again and try to simplify it.  One thing you'll notice in the codebase, is we try very hard to avoid `else` and especially `else if`.  When logic is structured cleanly, there is rarely a need for either.  If you have questions on how or what, please feel free to reach out.

Also be sure you have eslint installed in your editor.  there are some code style errors here that do not conform.

File: test/aircraft/FlightManagementSystem/Fms.spec.js [hunk 2]
```diff
@@ -654,14 +654,16 @@ ava('.replaceDepartureProcedure() does not call ._updateDepartureRunwayFromRoute
     t.deepEqual(responseForInvalidProcedure, expectedResponse);
 });
 
-ava('.replaceDepartureProcedure() calls ._updateDepartureRunwayFromRoute() when the departure procedure is applied successfully', (t) => {
+ava('.replaceDepartureProcedure() calls ._updateDepartureRunwayFromRoute() and updates route when the departure procedure is applied successfully', (t) => {
```
Comment (n8rzz) [inline test/aircraft/FlightManagementSystem/Fms.spec.js]: With the changes to `. replaceDepartureProcedure()`, I would expect to see, at minimum, 8 new tests to cover each of the new logical branches.  This is one of the main reasons why we try to avoid `else` and `else if`, it adds unnecessary logical branches and makes code difficult to read.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 3]
```diff
@@ -793,9 +793,21 @@ export default class Fms {
...
+            if(this.departureRunwayModel){
+                routeString = this.departureAirportModel.icao.toUpperCase() + this.departureRunwayModel.name + PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER + routeString;
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: @erikquinn there has to be an easier way to do this stuff.  This inline string building is not maintainable and just looks gross.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 1 above)
Comment (eoinbutler) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: So a question I have is what I can expect from the user. If I can assume either a two or three element entry, one of those branches can go away, but I don't know what's a more desirable command syntax:

`sid SID.EXIT` or `sid ENTRY.SID.EXIT`.

I prefer the former myself, but it leads to a second question - at some point the entry will have to be found and then preppended to the route. At which level is it best to do this - in `AircraftCommander`, `Pilot` or `Fms` ?

**Comment by eoinbutler** [comment]
@erikquinn Ok I think I understand, I can have a go at implementing it as you described. Previously the SID command was doing something strange involving randomly selected exit point, and the STAR required a full ENTRY.PROCEDURE.EXIT form.

**Comment by eoinbutler** [comment]
@erikquinn, before I go cleaning up and writing tests, can I get a check that the logic is as intended now? 

If the user gives a command `SID sidname`, the FMS looks at the route to find a valid exit of `sidname` and then replaces the route up to that point with `sidname`

If the user gives a command `SID sidname.exit`, the FMS looks to find find a way to merge with the current route.

It's not forbidden to give a command `SID runway.sidname.exit`, but I don't think that the additional `runway` affects the route 

TIA.

**Comment by n8rzz** [comment]
@erikquinn thoughts on @eoinbutler last comment?

**Comment by erikquinn** [comment]
@eoinbutler Sorry about the delay, I must have missed this notification somehow :grimacing:

Everything seems to work flawlessly in my testing of it, save for one thing mentioned below, so thank you very much! There are also some minor style changes and simplifications to the way you've written it that can be addressed in a review, but for now, two thumbs up.

The one issue I encountered was for an aircraft I rerouted to a single fix (HQM), then gave `sid summa1.bke`. The routes do not have continuity, but this message is not returned to the user-- it just silently errors in the console while you keep pressing enter and wondering why nothing happens. Easy fix for sure. If I instead did a `rr ksea16l.summa1.summa`, that yields the `Routes do not have continuity!` message we should be getting with the sid command.

:+1:

**Comment by eoinbutler** [comment]
I'm going to try and revive working on it. Summer and life have taken over.

File: src/assets/scripts/client/aircraft/AircraftCommander.js [hunk 4]
```diff
@@ -367,14 +367,14 @@ export default class AircraftCommander {
      * @for AircraftCommander
      * @method runSID
      * @param aircraft {AircraftModel}
-     * @param data {array}
+     * @param data {array<string>} a string representation of the SID}
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: done

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js [hunk 5]
```diff
@@ -293,37 +294,61 @@ export default class Pilot {
...
+            const procedureId = routeStringElements[0];
+            const sidModel = NavigationLibrary.getProcedure(procedureId);
+            if (_isNil(sidModel)) {
+                return [false, 'SID name not understood'];
+            }
+
+            const existingWaypoints = this._fms.waypoints;
+            let exitPoint = '';
+            for (let i = 0; i < existingWaypoints.length; i++) {
+                const waypoint = existingWaypoints[i];
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/Pilot/Pilot.js]: done

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js [hunk 6]
```diff
@@ -293,37 +294,61 @@ export default class Pilot {
      * @param airportIcao {string}          airport icao identifier
      * @return {array}                      [success of operation, readback]
      */
-    applyDepartureProcedure(procedureId, airportIcao) {
-        const procedureModel = NavigationLibrary.getProcedure(procedureId);
+    applyDepartureProcedure(routeString, airportIcao) {
+        let routeStringElements = routeString.split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/Pilot/Pilot.js]: done

File: test/aircraft/FlightManagementSystem/Fms.spec.js [hunk 7]
```diff
@@ -624,11 +624,11 @@ ava('.replaceDepartureProcedure() returns early when passed a wrong-length route
     // const navigationLibraryHasProcedureSpy = sinon.spy(fms._navigationLibrary, 'hasProcedure');
     const expectedResponse = [false, 'departure procedure format not understood'];
     const responseForSingleElement = fms.replaceDepartureProcedure('BOACH6');
-    const responseForDoubleElement = fms.replaceDepartureProcedure('KLAS07R.BOACH6');
+    //const responseForDoubleElement = fms.replaceDepartureProcedure('KLAS07R.BOACH6');
 
     // t.true(navigationLibraryHasProcedureSpy.notCalled);
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply test/aircraft/FlightManagementSystem/Fms.spec.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 8]
```diff
@@ -793,9 +793,21 @@ export default class Fms {
      * @return {boolean}
      */
     replaceDepartureProcedure(routeString) {
-        const routeStringElements = routeString.split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
-
-        if (routeStringElements.length !== 3) {
+        var routeStringElements = routeString.split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: should be `const ` now. We still need to figure out if there's a helper method.

@erikquinn

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 9]
```diff
@@ -799,20 +799,50 @@ export default class Fms {
...
+
         const procedureId = routeStringElements[1];
 
         if (!NavigationLibrary.hasProcedure(procedureId)) {
             return [false, `unknown procedure "${procedureId}"`];
         }
 
-        const wasSuccessful = this._routeModel.replaceDepartureProcedure(routeString);
+        const newRouteString = routeStringElements.join(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
+        const wasSuccessful = this._routeModel.replaceDepartureProcedure(newRouteString);
```
Comment (erikquinn) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: Please avoid using `new` in variable names. For instances like these, we like doing `nextRouteString`.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js [hunk 10]
```diff
@@ -772,26 +772,17 @@ export default class RouteModel extends BaseModel {
      * @return {boolean} whether operation was successful
      */
     replaceDepartureProcedure(routeString) {
-        let sidLegModel;
+        let sidModel;
```
Comment (erikquinn) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js]: It's not an instance of the SID definition, but rather an instance of a route which has only the SID leg. Thus, we should call this `sidRouteModel`. You can tell that will be a good name when we look down below and see we would then have `this.absorbRouteModel(sidRouteModel)`.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 11]
```diff
@@ -799,20 +799,50 @@ export default class Fms {
...
 
+        if (routeStringElements.length === 1) { // RouteString looks like PROC
+            const procedureId = routeStringElements[0];
+            const sidModel = NavigationLibrary.getProcedure(procedureId);
+
+            if (_isNil(sidModel)) {
+                return [false, 'SID name not understood'];
+            }
+
+            const exitPoint = _find(this._fms.waypoints, (waypointModel) => sidModel.hasExit(waypointModel.name));
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 12]
```diff
@@ -799,20 +799,50 @@ export default class Fms {
...
+
+            if (exitPoint === '') {
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 13]
```diff
@@ -799,20 +799,50 @@ export default class Fms {
...
+                return [false, `SID ${procedureId.toUpperCase()} doesn't have an exit along our route`];
+            }
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

**Comment by felixscheffer** [comment]
Honestly, I am not happy with this PR. One of the things that bug me is, that we treat SIDs and STARs very differently in the RouteModel now.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js (hunk 10 above)
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/RouteModel.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 9 above)
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/AircraftCommander.js [hunk 14]
```diff
@@ -367,14 +367,14 @@ export default class AircraftCommander {
      * @for AircraftCommander
      * @method runSID
      * @param aircraft {AircraftModel}
-     * @param data {array}
+     * @param data {array<string>} a string representation of the SID
```
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: done

**Comment by felixscheffer** [comment]
I finally fixed the tests. I also did some testing at EDDF and it seems to work fine.

File: src/assets/scripts/client/aircraft/AircraftCommander.js [hunk 15]
```diff
@@ -367,14 +367,14 @@ export default class AircraftCommander {
      * @for AircraftCommander
      * @method runSID
      * @param aircraft {AircraftModel}
-     * @param data {array}
+     * @param data {array<string>} a string representation of the SID (may also include exit, eg sid.exit)
      * @return {array}   [success of operation, readback]
      */
     runSID(aircraft, data) {
-        const sidId = data[0];
+        const routeString = data[0].toUpperCase();
```
[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: Looks like this is because they are imported without amending the casing from the airport files. They are written in the files in upper case, and so when trying to look one up, they are stored in upper case and obviously won't match if we don't do this. I think SIDs/STARs/fixes/airways are the only cases where they are stored in upper case, all for the same reason. Since they are _always_ shown in upper case, it kinda makes sense to leave it upper case rather than casing it down just to case it back up later.

[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: If nothing else though, it seems safer to do the upper-casing in the FMS, where the comparison happens, that way other methods calling through different stacks will still get the right result regardless of their casing.

[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: Moved `.toUpperCase()` to the FMS.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 16]
```diff
@@ -799,28 +800,66 @@ export default class Fms {
...
+    replaceDepartureProcedure(routeString, airportIcao) {
         const routeStringElements = routeString.split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
 
-        if (routeStringElements.length !== 3) {
+        if (routeStringElements.length > 3) {
             return [false, 'departure procedure format not understood'];
         }
 
-        const procedureId = routeStringElements[1];
+        const procedureId = routeStringElements.length <= 2 ?
```
[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js [hunk 17]
```diff
@@ -295,6 +295,19 @@ export default class ProcedureModel {
...
+     * Return the name of the first entry point if there is exactly one entry point.
+     *
+     * @for ProcedureModel
+     * @method getUniqueEntryPoint
+     * @return {string}
+     */
+    getUniqueEntryPoint() {
+        const entryNames = Object.keys(this._entryPoints);
+
+        return entryNames.length === 1 ? entryNames[0] : null;
```
[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: both done

File: src/assets/scripts/client/aircraft/AircraftCommander.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (felixscheffer) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: FYI if you type in something like `sid EDDF18.OBOKA1L.OBOKA` the route string will end up as "eddf18.oboka1l.oboka", i.e. lower case even though typed in as upper-case. And as a result of that, trying to find the corresponding procedure will always fail, because procedures are stored in upper-case. 

The upper-case/lower-case issue is the original bug reported in  #955. Anything else in this PR are changes that were requested later by @erikquinn.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 8 above)
[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: no helper at the moment. we could add it since there is a good number of these around, but it's not super important.

File: test/aircraft/FlightManagementSystem/Fms.spec.js (hunk 2 above)
Comment (erikquinn) [reply test/aircraft/FlightManagementSystem/Fms.spec.js]: some tests have been added

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 3 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: i agree, but idk what that would be... :/

File: test/aircraft/FlightManagementSystem/Fms.spec.js [hunk 18]
```diff
@@ -654,14 +654,16 @@ ava('.replaceDepartureProcedure() does not call ._updateDepartureRunwayFromRoute
...
     const fms = buildFmsForAircraftInApronPhaseWithRouteString(fullRouteStringMock);
     const updateDepartureRunwayFromRouteSpy = sinon.spy(fms, '_updateDepartureRunwayFromRoute');
     const expectedResponse = [true, ''];
-    const response = fms.replaceDepartureProcedure('KLAS07R.BOACH6.TNP');
+    const proposedRoute = 'KLAS07R.BOACH6.TNP'
+    const response = fms.replaceDepartureProcedure(proposedRoute);
 
     t.true(updateDepartureRunwayFromRouteSpy.calledWithExactly());
     t.deepEqual(response, expectedResponse);
+    t.true(proposedRoute + fullRouteStringMock.substring(18) === fms.getRouteString())
```
[the remark this answers is not in the document]
Comment (erikquinn) [reply test/aircraft/FlightManagementSystem/Fms.spec.js]: seems like this check has been removed; is that intentional?

File: test/aircraft/FlightManagementSystem/Fms.spec.js [hunk 19]
```diff
@@ -624,11 +624,11 @@ ava('.replaceDepartureProcedure() returns early when passed a wrong-length route
     // const navigationLibraryHasProcedureSpy = sinon.spy(fms._navigationLibrary, 'hasProcedure');
     const expectedResponse = [false, 'departure procedure format not understood'];
     const responseForSingleElement = fms.replaceDepartureProcedure('BOACH6');
-    const responseForDoubleElement = fms.replaceDepartureProcedure('KLAS07R.BOACH6');
+    //const responseForDoubleElement = fms.replaceDepartureProcedure('KLAS07R.BOACH6');
 
     // t.true(navigationLibraryHasProcedureSpy.notCalled);
     t.deepEqual(responseForSingleElement, expectedResponse);
-    t.deepEqual(responseForDoubleElement, expectedResponse);
+    //t.deepEqual(responseForDoubleElement, expectedResponse);
```
[the remark this answers is not in the document]
Comment (erikquinn) [reply test/aircraft/FlightManagementSystem/Fms.spec.js]: done

File: src/assets/scripts/client/aircraft/AircraftCommander.js (hunk 15 above)
[the remark this answers is not in the document]
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/AircraftCommander.js]: It works for now.

Created #1173 for @n8rzz's sanity 😄

File: test/aircraft/FlightManagementSystem/Fms.spec.js (hunk 18 above)
[the remark this answers is not in the document]
Comment (felixscheffer) [reply test/aircraft/FlightManagementSystem/Fms.spec.js]: still there:

`t.true(expectedRouteString === fms.getRouteString());`

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 20]
```diff
@@ -799,28 +800,68 @@ export default class Fms {
...
+            const runwayModel = this.departureRunwayModel;
+
+            if (_isNil(runwayModel)) {
+                return [false, 'unsure if we can accept that procedure; we don\'t have a runway assignment'];
+            }
+
+            let entryName = sidModel.getUniqueEntryPoint();
+
+            if (_isEmpty(entryName)) {
+                entryName = airportIcao.toUpperCase() + runwayModel.name;
```
Comment (erikquinn) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: L839-L852 don't make sense to me. If they're assigned a new route on the ground, they should accept it and expect to be taxiied to a runway which is valid for that SID. Thus, they should not reject the route as they do below. The behavior as written here is this:
- If there is only one runway which is valid for the requested SID, then expect that runway and enter the route into the FMS
- If there either multiple runways, or _no_ runways, which are valid for the requested SID, reject the route.

It should be this:
- If the current expected departure runway _is_ valid for the requested SID, then apply the route using the currently expected departure runway.
- If the current expected departure runway is not valid for the requested SID, expect any runway which _is_ valid. The aircraft must not be allowed to depart until it is taxiied to a runway which is valid for the SID.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 21]
```diff
@@ -835,28 +836,83 @@ export default class Fms {
...
+					log: `the ${procedureId.toUpperCase()} departure has no valid entrypoint`,
+					say: `the ${procedureId.toUpperCase()} departure has no valid entrypoint`
+				};
+				return [false, negativeReadback];			
+			}
+				
+					
+           
+			routeStringElements.unshift(entryName);
+
```
Comment (felixscheffer) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: remove blank line

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 22]
```diff
@@ -835,28 +836,83 @@ export default class Fms {
...
+			}
+			if (_isEmpty(entryName)) {
+				const negativeReadback = {
+					log: `the ${procedureId.toUpperCase()} departure has no valid entrypoint`,
+					say: `the ${procedureId.toUpperCase()} departure has no valid entrypoint`
+				};
+				return [false, negativeReadback];			
+			}
+				
+
```
Comment (felixscheffer) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: only one blank line

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 23]
```diff
@@ -835,28 +836,83 @@ export default class Fms {
...
+				else{
+					entryName=runwayEntryPoint;
+				}
+			}
+			if (_isEmpty(entryName)) {
+				const negativeReadback = {
+					log: `the ${procedureId.toUpperCase()} departure has no valid entrypoint`,
+					say: `the ${procedureId.toUpperCase()} departure has no valid entrypoint`
+				};
+				return [false, negativeReadback];
```
Comment (felixscheffer) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: add blank line before return

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 24]
```diff
@@ -835,28 +836,83 @@ export default class Fms {
...
+			
+					
+			if (this.currentPhase!==FLIGHT_PHASE.APRON){
+				let runwayEntryPoint=airportIcao.toUpperCase() + runwayModel.name;
+				if (!sidModel.hasEntry(runwayEntryPoint)) {
+					const negativeReadback = {
+                        log: `the ${procedureId.toUpperCase()} departure is not valid for runway ${runwayModel.name}`,
+                        say: `the ${procedureId.toUpperCase()} departure is not valid for runway ${radio_runway(runwayModel.name)}`
+                    };
+                    return [false, negativeReadback];
```
Comment (felixscheffer) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: blank line before return. incorrect indent

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 25]
```diff
@@ -835,28 +836,83 @@ export default class Fms {
...
+                }
```
Comment (felixscheffer) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: incorrect indent

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 26]
```diff
@@ -835,28 +836,83 @@ export default class Fms {
...
+        if (routeStringElements.length === 2) { // RouteString looks like PROC.EXIT
+            const runwayModel = this.departureRunwayModel;
+
+            if (_isNil(runwayModel)) {
+                return [false, 'unsure if we can accept that procedure; we don\'t have a runway assignment'];
+            }
+
+            let entryName = sidModel.getFirstEntryPoint();
+
+
```
Comment (felixscheffer) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: only one blank line

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 27]
```diff
@@ -804,7 +805,7 @@ export default class Fms {
      * @return {array<boolean, string>}
      */
     replaceArrivalProcedure(routeString) {
-        const routeStringElements = routeString.split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
+        const routeStringElements = routeString.toUpperCase().split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: please remove this `.toUpperCase()` here.  have have, and continue to try, to normalize casing as `lowercase`.  even so, casing shouldn't matter here if you are doing a split.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 28]
```diff
@@ -835,28 +836,83 @@ export default class Fms {
      * @param routeString {string}
      * @return {boolean}
      */
-    replaceDepartureProcedure(routeString) {
-        const routeStringElements = routeString.split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
+    replaceDepartureProcedure(routeString, airportIcao) {
+        const routeStringElements = routeString.toUpperCase().split(PROCEDURE_OR_AIRWAY_SEGMENT_DIVIDER);
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: same thing here, please remove `toUpperCase()` (see previous comment)

File: test/aircraft/FlightManagementSystem/Fms.spec.js [hunk 29]
```diff
@@ -593,10 +585,10 @@ ava('.replaceDepartureProcedure() returns early when the specified procedure doe
 });
 
 ava('.replaceDepartureProcedure() does not call ._updateDepartureRunwayFromRoute() when the departure procedure is not applied successfully', (t) => {
+    const expectedResponse = [false, 'route of "KLAS07R.BOACH6.TNP" is not valid'];
     const fms = buildFmsForAircraftInApronPhaseWithRouteString(fullRouteStringMock);
-    const routeModelReplaceDepartureProcedureStub = sinon.stub(fms._routeModel, 'replaceDepartureProcedure', () => false);
+    const routeModelReplaceDepartureProcedureStub = sinon.stub(fms._routeModel, 'replaceDepartureProcedure', () => expectedResponse);
```
Comment (n8rzz) [inline test/aircraft/FlightManagementSystem/Fms.spec.js]:
```suggestion
    const routeModelReplaceDepartureProcedureStub = sinon.stub(fms._routeModel, 'replaceDepartureProcedure').returns(expectedResponse);
```

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 30]
```diff
@@ -835,28 +836,83 @@ export default class Fms {
...
+                return [false, 'unsure if we can accept that procedure; we don\'t have a runway assignment'];
+            }
+
+            let entryName = sidModel.getFirstEntryPoint();
+
+			
+			
+			
+					
+			if (this.currentPhase!==FLIGHT_PHASE.APRON){
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: yikes, this whole section needs some formatting love.  Be sure you have both editorconfig and eslint plugins installed in your editor/ide.  Also be sure your code looks like existing code.

I'll hold off an any additional reviews for this section until after it's been formatted correctly

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js [hunk 31]
```diff
@@ -289,41 +288,22 @@ export default class Pilot {
...
         this.hasDepartureClearance = true;
 
-        this._mcp.setAltitudeVnav();
-        this._mcp.setSpeedVnav();
-        this._fms.replaceDepartureProcedure(routeString);
-
         const readback = {};
-        readback.log = `cleared to destination via the ${procedureId} departure, then as filed`;
-        readback.say = `cleared to destination via the ${procedureModel.name} departure, then as filed`;
+        readback.log = `cleared to destination via the ${this._fms._routeModel.getSidIcao().toUpperCase()} departure, then as filed`;
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/Pilot/Pilot.js]: please set `this._fms._routeModel.getSidIcao().toUpperCase()` to a constant first above the `readback` initialization.

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js [hunk 32]
```diff
@@ -294,6 +294,38 @@ export default class ProcedureModel {
...
+	
+	
+	  /**
+     * Return the name of the first entry point
+     *
+     * @for ProcedureModel
+     * @method getFirstEntryPoint
+     * @return {string}
+     */
+    getFirstEntryPoint() {
```
Comment (n8rzz) [inline src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: see previous comment about editorconfig/eslint.  I'll hold on a review of this section until then

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js [hunk 33]
```diff
@@ -294,6 +294,38 @@ export default class ProcedureModel {
...
+        const entryNames = Object.keys(this._entryPoints);
```
Comment (n8rzz) [inline src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: if you're grabbing keys off an object are expecting a certain sort order?  if this is coming off an object, _first_ entry is somewhat arbitrary because an objects keys are not going to be in a guaranteed order.

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js [hunk 34]
```diff
@@ -294,6 +294,38 @@ export default class ProcedureModel {
...
+    }
+
+    /**
+     * Return the name of the first entry point if there is exactly one entry point.
+     *
+     * @for ProcedureModel
+     * @method getUniqueEntryPoint
+     * @return {string}
+     */
+    getUniqueEntryPoint() {
```
Comment (n8rzz) [inline src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: please be sure to add some tests for this method

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js (hunk 32 above)
Comment (n8rzz) [inline src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: please be sure to add some tests for this method

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 24 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 25 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 26 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 27 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 28 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 30 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: done

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js (hunk 31 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/Pilot/Pilot.js]: done

File: test/aircraft/FlightManagementSystem/Fms.spec.js (hunk 29 above)
Comment (erikquinn) [reply test/aircraft/FlightManagementSystem/Fms.spec.js]: done

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js (hunk 33 above)
Comment (erikquinn) [reply src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: If this is used for what I think it is, then _which_ element is returned is actually irrelevant. Looking into it. Would be in reference to the above comment:
> If the current expected departure runway is not valid for the requested SID, expect any runway which is valid. The aircraft must not be allowed to depart until it is taxiied to a runway which is valid for the SID.

Either way, there should definitely be some explanations to this effect in the docblock.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 27 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: @n8rzz actually, this one is needed. They are stored as uppercase in the routemodel.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 28 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: @n8rzz actually, this one is needed. They are stored as uppercase in the routemodel.

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js (hunk 33 above)
Comment (erikquinn) [reply src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: assumption confirmed, docblock improved

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 27 above)
Comment (n8rzz) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: I know you want to get this in soon, could you add a comment to these as a reminder to do this in a less-dirty way?  I feel like this can be solved in a better way

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 35]
```diff
@@ -835,28 +836,58 @@ export default class Fms {
...
-        if (routeStringElements.length !== 3) {
+        if (routeStringElements.length > 3) {
             return [false, 'departure procedure format not understood'];
         }
 
-        const procedureId = routeStringElements[1];
+        let procedureId = routeStringElements[0];
 
-        if (!NavigationLibrary.hasProcedure(procedureId)) {
+        if (routeStringElements.length === 3) {
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: lets add a comment here too to make this cleaner.

we could use a `switch` on the length and then fire off smaller methods based on the length.  we can tackle that later, though

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 36]
```diff
@@ -835,28 +836,58 @@ export default class Fms {
...
+            }
 
-            return [true, ''];
+            routeStringElements.push(exitPoint.name);
         }
 
-        return [false, `route of "${routeString}" is not valid`];
+        if (routeStringElements.length === 2) { // RouteString looks like PROC.EXIT
+            const expectedRunwayModel = this.departureRunwayModel;
+            let entryPoint = airportIcao.toUpperCase() + expectedRunwayModel.name; // sidModel.getFirstEntryPoint();
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]:
```suggestion
            let entryPoint = `${airportIcao}${expectedRunwayModel.name}`; // sidModel.getFirstEntryPoint();
```

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js [hunk 37]
```diff
@@ -835,28 +836,58 @@ export default class Fms {
...
+
+            if (!sidModel.hasEntry(entryPoint)) {
+                entryPoint = sidModel.getFirstEntryPoint();
+
+                if (_isEmpty(entryPoint)) {
+                    throw new TypeError(`the '${procedureId}' departure has no valid entry points`);
+                }
+            }
+
+            routeStringElements.unshift(entryPoint);
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: we should really work to normalize casing with the routeString.  remember the old day's with `.toLowerCase()` and `.toUpperCase()` all over the place?  I don't want to go back to that.  Data comes in, we normalize to lower.  Data goes out, we transform to whats needed only then and never anywhere else in between.

```suggestion
            routeStringElements.unshift(entryPoint.toUpperCase());
```

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js [hunk 38]
```diff
@@ -289,41 +288,25 @@ export default class Pilot {
...
         }
 
         this.hasDepartureClearance = true;
 
-        this._mcp.setAltitudeVnav();
-        this._mcp.setSpeedVnav();
-        this._fms.replaceDepartureProcedure(routeString);
-
+        // FIXME: We should not be accessing a private property of the Fms directly from the AircraftModel like this
+        const sidIcao = this._fms._routeModel.getSidIcao().toUpperCase();
```
Comment (n8rzz) [inline src/assets/scripts/client/aircraft/Pilot/Pilot.js]: we should also move the `.toUpperCase()`es down to the template string

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js [hunk 39]
```diff
@@ -295,6 +295,48 @@ export default class ProcedureModel {
         return exitNames[randomIndex];
     }
 
+      /**
```
Comment (n8rzz) [inline src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: extra spaces

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 35 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: added the comment.

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 36 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: 👍 done

File: src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js (hunk 37 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/FlightManagementSystem/Fms.js]: I agree, but the problems with that are widespread with the routes already. Should be addressed as part of #1173.

File: src/assets/scripts/client/aircraft/Pilot/Pilot.js (hunk 38 above)
Comment (erikquinn) [reply src/assets/scripts/client/aircraft/Pilot/Pilot.js]: ok, done

File: src/assets/scripts/client/navigationLibrary/ProcedureModel.js (hunk 39 above)
Comment (erikquinn) [reply src/assets/scripts/client/navigationLibrary/ProcedureModel.js]: thanks, good catch 👍

**Comment by seppl831** [comment]
I got the message about formatting and i must admit i did the changes with notepad++ and not an ide... 
Still I'm pretty sure your solution will cause errors when changing the sid while an airplane is already waiting at a runway...
But I'm happy I can use the sid command now and will leave the coding up to you guys.
